version: '3'

services:
  mssql:
    image: mcr.microsoft.com/mssql/rhel/server:2022-latest
    container_name: 'mssql2022-latest-rhel'
    environment:
      - MSSQL_SA_PASSWORD=<your_strong_password>
      - ACCEPT_EULA=Y
      # - MSSQL_PID=<your_product_id> # default: Developer
      # - MSSQL_PID=Express
      # - MSSQL_PID=Standard
      # - MSSQL_PID=Enterprise
      # - MSSQL_PID=EnterpriseCore
    ports:
      - 1433:1433
    volumes:
      - ./mssql/log:/var/opt/mssql/log
      - ./mssql/data:/var/opt/mssql/data
